"""add_store_business_fields

Revision ID: 90b83d001dbe
Revises: 54b220decf93
Create Date: 2026-03-14 23:46:15.441436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b83d001dbe'
down_revision = '54b220decf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=180), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('contact_email')
        batch_op.drop_column('phone')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('address')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
