ALTER TABLE users ADD COLUMN IF NOT EXISTS street TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS street_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS neighborhood TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS zip_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS apartment TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS complement TEXT;
